on:
  push:
    branches: [ main ]

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "*"
          target: "public_html"
